# Numpy: package for multi-dimensional arrays

### Numpy is helpful to play with array(numbers)
### whereas pandas are useful to deal with data sets
### MatplotLib is use to deal with data visualisation
### Seaborn is used for data visualisation
### Scipy is used for doing statistical analysis
### Sklearn is used to do all the algorithmic perspective

### num stands for numerical and py stands for python

### Step1: import the package numpy

In [5]:
import numpy as np

### np.array stores the given values in the array

In [4]:

simple_list=[1,2,3]
np.array(simple_list)

array([1, 2, 3])

In [7]:
array=np.array([1,2,34])
array

array([ 1,  2, 34])

In [8]:
list_of_lists=[[1,2],[3,4],[5,6]]
np.array([list_of_lists])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

### aranges gives us the range starts from the 1st digit that we have entered till the last element-1
### ex:if the numbers are arange(1,5)then the output is 1,2,3,4

In [17]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### if we don't specify any start number then the start number will be considered as zero(by default)

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

### here 5 is the step size so,every element has 5 step differenceby default the step size will be 1 without considering the last digit

In [21]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [23]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

### zeros()->produces a array with elements as zeros as float type i.e.,0.

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(3)

array([0., 0., 0.])

### zeros(num,int)-> produces an array with all elements as zeros in integer type with num size 

In [26]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### np.ones((rows,columns))->gives us a multididimensional array with all the elements as 1 in float type(1.)
### and ones((rows,columns),int)->array with 1's in integer type

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### linspace()  means linear space here the 1st digit in o/p is 0 and last digit in the o/p willbe 2 and there will be 5 digits in the output int the float data type 

In [6]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [7]:
np.linspace(0,2,8)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

### np.eye() gives an identity matrix 
### ex:here 10 rows and 10 coloumns identitymatrix will be produced in float type if we want it in integer type we should use dtype=int

In [8]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [9]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### random.rand(rows,columns) generates random number in 3 rows and 5 columns(from below ex)and the random numbers ranging from 0 to 1

In [10]:
np.random.rand(3,5)

array([[0.77037712, 0.93734153, 0.62751639, 0.48394852, 0.00555664],
       [0.70078742, 0.4240927 , 0.03764895, 0.28984323, 0.56384192],
       [0.39592459, 0.13292419, 0.23706341, 0.43552364, 0.13150404]])

### random numbers including neagative floating values

In [11]:
np.random.randn(2,4)

array([[-0.33784117, -2.7893505 , -0.48333813,  1.86581826],
       [ 0.38776625,  1.4630948 , -0.45763534, -0.38998169]])

### ranom.randint() generates an integer ex:random.randint(1,10)->generates a random number between 1 to 10

In [13]:
np.random.randint(1,100)

64

### generates 50 random numbers between 20 and 59 and stoed in array

In [14]:
np.random.randint(20,60,50)

array([25, 47, 56, 52, 38, 47, 28, 51, 21, 37, 47, 57, 57, 40, 25, 57, 52,
       34, 59, 36, 40, 50, 42, 29, 51, 52, 59, 47, 28, 30, 22, 41, 42, 44,
       57, 52, 24, 42, 21, 40, 38, 43, 23, 27, 41, 38, 54, 56, 44, 42])

In [18]:
sample_arr=np.arange(30)
sample_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
rand_arr=np.random.randint(1,50,30)
rand_arr

array([ 9,  2,  1, 27, 22, 46,  4, 30, 25,  1, 39, 20, 47, 36, 47, 20, 17,
       47, 30, 20, 46, 21,  2, 48, 11, 16, 30, 17, 49, 31])

### array.reshape(rows,columns)-> reshapes the array into a matrix in rows and columns

In [23]:
sample_arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
sample_arr.reshape(4,2)

ValueError: cannot reshape array of size 30 into shape (4,2)

### array.max()-> returns the maximum value in the array
### array.argmax()-> returns the index of the maximum value in the array

In [25]:
rand_arr.max()

49

In [26]:
rand_arr.argmax()

28

### a.t-> here t means transposeof the identity matrix

In [27]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
sample_array[0]

10

### [2:5]-> prints the elements in the index 2to 4 i.e.,12,13,14

In [32]:
sample_array[2:5]

array([12, 13, 14])

In [33]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [35]:
sample_array=np.arange(10,21)

In [36]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [37]:
subset_array=sample_array[0:7]
subset_array

array([10, 11, 12, 13, 14, 15, 16])

### changing all the elements as 1001 i.e.,[:]=1001

In [38]:
subset_array[:]=1001
subset_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Multi dimensional arrays

In [1]:
import numpy as np

In [5]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [10]:
sample_matrix[1,2]

21

### here : indicates all i.e.,all rows or all coulmns

In [11]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [12]:
sample_matrix[1]

array([24, 23, 21, 33])

In [14]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

### Selection techninques

In [20]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [21]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [19]:
np.exp(sample_array)           #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [22]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [23]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [24]:
np.max(sample_array)

19

In [25]:
np.min(sample_array)

1

In [26]:
np.argmax(sample_array)

18

In [27]:
np.argmin(sample_array)

0

In [28]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [29]:
np.std(sample_array)

5.477225575051661

In [30]:
np.var(sample_array)

30.0

In [31]:
np.mean(sample_array)

10.0

In [34]:
array=np.random.randn(3,4)
array

array([[ 0.7521053 ,  0.34325958,  0.5740892 , -0.78416418],
       [-0.66948177,  0.9650579 , -0.01467496, -0.65668458],
       [-0.49198167, -0.74618717,  0.72356877, -1.28004142]])

### np.round()->rounds the decimal values to the desired digits

In [37]:
sports=np.array(['golf','cricket','fball','cricket'])
sports

array(['golf', 'cricket', 'fball', 'cricket'], dtype='<U7')

### np.unique()->eliminates the repeating values and prints all the values without any repetition

In [38]:
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

# Pandas

In [2]:
import pandas as pd
import numpy as np

# Pandas Dataframe and Indexing

### pd.Series is used for uni-dimensional data
### whereas pd.DataFrame is used for multi-dimensional data

In [18]:
sports1=pd.Series([1,2,3,4],index=["cricket","football","basketball","golf"])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [19]:
sports1["football"]

2

In [20]:
sports2=pd.Series([11,2,3,4],index=["cricket","football","bseball","golf"])
sports2

cricket     11
football     2
bseball      3
golf         4
dtype: int64

### if the element is not present in the both tables then the addition returns Nan which indicates not a number

In [21]:
sports1+sports2


basketball     NaN
bseball        NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [23]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns="score1 score2 score3 score4 score5".split())
df1

score1    score2    score3    score4    score5
A  0.932521  0.651458  0.875157  0.969127  0.696986
B  0.378595  0.064071  0.560443  0.443245  0.071482
C  0.880992  0.485642  0.928735  0.902190  0.084356
D  0.640975  0.922837  0.809029  0.015150  0.906537
E  0.878942  0.397704  0.436628  0.905730  0.793199
F  0.427878  0.118425  0.855081  0.987718  0.485240
G  0.644530  0.747743  0.710265  0.870171  0.537043
H  0.047607  0.173125  0.444792  0.997720  0.784838

In [24]:
df1['score1']

A    0.932521
B    0.378595
C    0.880992
D    0.640975
E    0.878942
F    0.427878
G    0.644530
H    0.047607
Name: score1, dtype: float64

In [28]:
df1[['score1','score2','score3']]

score1    score2    score3
A  0.932521  0.651458  0.875157
B  0.378595  0.064071  0.560443
C  0.880992  0.485642  0.928735
D  0.640975  0.922837  0.809029
E  0.878942  0.397704  0.436628
F  0.427878  0.118425  0.855081
G  0.644530  0.747743  0.710265
H  0.047607  0.173125  0.444792

In [30]:
df1["score6"]=df1["score1"]+df1["score2"]
df1['score6']

A    1.583979
B    0.442666
C    1.366634
D    1.563812
E    1.276646
F    0.546303
G    1.392273
H    0.220732
Name: score6, dtype: float64

In [4]:
df2={'Id':[101,102,103,104,105],'name':["joe","james","john","jack","jenny"],'profit':[20,30,40,50,60]}
df=pd.DataFrame(df2)
df

Id   name  profit
0  101    joe      20
1  102  james      30
2  103   john      40
3  104   jack      50
4  105  jenny      60

In [6]:
df[['name','profit']]

name  profit
0    joe      20
1  james      30
2   john      40
3   jack      50
4  jenny      60

In [7]:
df["Id"]

0    101
1    102
2    103
3    104
4    105
Name: Id, dtype: int64

### drop("column_name",axis= column_no)==>drops(deletes) a column 
### drop(3)==>deletes the 3rd row in the data frame

In [8]:
df.drop("Id",axis=1)

name  profit
0    joe      20
1  james      30
2   john      40
3   jack      50
4  jenny      60

In [9]:
df.drop(3)

Id   name  profit
0  101    joe      20
1  102  james      30
2  103   john      40
4  105  jenny      60