# Numpy: package for multi-dimensional arrays

### Numpy is helpful to play with array(numbers)
### whereas pandas are useful to deal with data sets
### MatplotLib is use to deal with data visualisation
### Seaborn is used for data visualisation
### Scipy is used for doing statistical analysis
### Sklearn is used to do all the algorithmic perspective

### num stands for numerical and py stands for python

### Step1: import the package numpy

In [5]:
import numpy as np

### np.array stores the given values in the array

In [4]:

simple_list=[1,2,3]
np.array(simple_list)

array([1, 2, 3])

In [7]:
array=np.array([1,2,34])
array

array([ 1,  2, 34])

In [8]:
list_of_lists=[[1,2],[3,4],[5,6]]
np.array([list_of_lists])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

### aranges gives us the range starts from the 1st digit that we have entered till the last element-1
### ex:if the numbers are arange(1,5)then the output is 1,2,3,4

In [17]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### if we don't specify any start number then the start number will be considered as zero(by default)

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

### here 5 is the step size so,every element has 5 step differenceby default the step size will be 1 without considering the last digit

In [21]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [23]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

### zeros()->produces a array with elements as zeros as float type i.e.,0.

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(3)

array([0., 0., 0.])

### zeros(num,int)-> produces an array with all elements as zeros in integer type with num size 

In [26]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### np.ones((rows,columns))->gives us a multididimensional array with all the elements as 1 in float type(1.)
### and ones((rows,columns),int)->array with 1's in integer type

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### linspace()  means linear space here the 1st digit in o/p is 0 and last digit in the o/p willbe 2 and there will be 5 digits in the output int the float data type 

In [6]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [7]:
np.linspace(0,2,8)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

### np.eye() gives an identity matrix 
### ex:here 10 rows and 10 coloumns identitymatrix will be produced in float type if we want it in integer type we should use dtype=int

In [8]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [9]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### random.rand(rows,columns) generates random number in 3 rows and 5 columns(from below ex)and the random numbers ranging from 0 to 1

In [10]:
np.random.rand(3,5)

array([[0.77037712, 0.93734153, 0.62751639, 0.48394852, 0.00555664],
       [0.70078742, 0.4240927 , 0.03764895, 0.28984323, 0.56384192],
       [0.39592459, 0.13292419, 0.23706341, 0.43552364, 0.13150404]])

### random numbers including neagative floating values

In [11]:
np.random.randn(2,4)

array([[-0.33784117, -2.7893505 , -0.48333813,  1.86581826],
       [ 0.38776625,  1.4630948 , -0.45763534, -0.38998169]])

### ranom.randint() generates an integer ex:random.randint(1,10)->generates a random number between 1 to 10

In [13]:
np.random.randint(1,100)

64

### generates 50 random numbers between 20 and 59 and stoed in array

In [14]:
np.random.randint(20,60,50)

array([25, 47, 56, 52, 38, 47, 28, 51, 21, 37, 47, 57, 57, 40, 25, 57, 52,
       34, 59, 36, 40, 50, 42, 29, 51, 52, 59, 47, 28, 30, 22, 41, 42, 44,
       57, 52, 24, 42, 21, 40, 38, 43, 23, 27, 41, 38, 54, 56, 44, 42])

In [18]:
sample_arr=np.arange(30)
sample_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
rand_arr=np.random.randint(1,50,30)
rand_arr

array([ 9,  2,  1, 27, 22, 46,  4, 30, 25,  1, 39, 20, 47, 36, 47, 20, 17,
       47, 30, 20, 46, 21,  2, 48, 11, 16, 30, 17, 49, 31])

### array.reshape(rows,columns)-> reshapes the array into a matrix in rows and columns

In [23]:
sample_arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
sample_arr.reshape(4,2)

ValueError: cannot reshape array of size 30 into shape (4,2)

### array.max()-> returns the maximum value in the array
### array.argmax()-> returns the index of the maximum value in the array

In [25]:
rand_arr.max()

49

In [26]:
rand_arr.argmax()

28

### a.t-> here t means transposeof the identity matrix

In [27]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
sample_array[0]

10

### [2:5]-> prints the elements in the index 2to 4 i.e.,12,13,14

In [32]:
sample_array[2:5]

array([12, 13, 14])

In [33]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [35]:
sample_array=np.arange(10,21)

In [36]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [37]:
subset_array=sample_array[0:7]
subset_array

array([10, 11, 12, 13, 14, 15, 16])

### changing all the elements as 1001 i.e.,[:]=1001

In [38]:
subset_array[:]=1001
subset_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])